version: "3.9"
services:
  dev:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
      - "5174:5174" # Vite uses this port for HMR
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80" # Nginx serves on port 80 in production
    environment:
      - NODE_ENV=production
